on:
  push:
    branches:
      - master

name: Serverless Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Register .env
      working-directory: ./serverless
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_US_PHONE_NUMBER: ${{ secrets.TWILIO_US_PHONE_NUMBER }}
        KINTONE_API_TOKEN: ${{ secrets.KINTONE_API_TOKEN }}
        KINTONE_BASE_URL: ${{ secrets.KINTONE_BASE_URL }}
        KINTONE_APP_ID: ${{ secrets.KINTONE_APP_ID }}
        LINE_NOTIFY_CLIENT_ID: ${{ secrets.LINE_NOTIFY_CLIENT_ID }}
        LINE_NOTIFY_CLIENT_SECRET: ${{ secrets.LINE_NOTIFY_CLIENT_SECRET }}
      run: |
        echo "TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}" >> ./.env
        echo "TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}" >> ./.env
        echo "TWILIO_US_PHONE_NUMBER=${TWILIO_US_PHONE_NUMBER}" >> ./.env
        echo "KINTONE_API_TOKEN=${KINTONE_API_TOKEN}" >> ./.env
        echo "KINTONE_BASE_URL=${KINTONE_BASE_URL}" >> ./.env
        echo "KINTONE_APP_ID=${KINTONE_APP_ID}" >> ./.env
        echo "LINE_NOTIFY_CLIENT_ID=${LINE_NOTIFY_CLIENT_ID}" >> ./.env
        echo "LINE_NOTIFY_CLIENT_SECRET=${LINE_NOTIFY_CLIENT_SECRET}" >> ./.env
    - name: yarn install
      working-directory: ./serverless
      run: yarn install
    - name: serverless package and deploy
      working-directory: ./serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn run serverless package --stage production --package ./build
        yarn run serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
        yarn run serverless deploy --stage production --package ./build